import "./globals.css";
import type { Metadata } from "next";
import { Share_Tech_Mono } from "next/font/google";
import Providers from "../components/providers";

const shareTechMono = Share_Tech_Mono({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Mars Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={shareTechMono.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
